### ISSUE TITLE
Erro python ao descarregar dados

### ISSUE THREAD

**Issue by Anabatalha** [frcaldeira/downloadgeostatportugal#2]
![erro](https://user-images.githubusercontent.com/104194201/164646189-a54965e0-81b0-4875-b123-a5d309441716.JPG)

**Comment by frcaldeira** [comment]
Olá Ana, experimente sff criar a pasta dados_INE  dentro da sua pasta c:\\users\anabatalha\appData\Roaming\QGIS3\profiles\default\python\plugin\downloadgeostatportugal

e teste novamente sff


Obrigado
Francisco

**Comment by jonnyforestGIS** [comment]
@frcaldeira se tudo correu bem com o merge das alterações. Então este issue pode ser fechado. Abraço

**Comment by gioman** [comment]
Este report parece ser ainda valido:

```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users/giovanni/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\downloadgeostatportugal/dados_INE/BGRI21_raa.zip' 
Traceback (most recent call last):
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\downloadgeostatportugal\downloadGeoStatPortugal.py", line 453, in 
    self.dlg.pB_Download.clicked.connect(lambda:self.button_DownloadData())
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\downloadgeostatportugal\downloadGeoStatPortugal.py", line 419, in button_DownloadData
    self.downloadData (SelectedGeography, SelectedYear, getChildNodeLevel)
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\downloadgeostatportugal\downloadGeoStatPortugal.py", line 274, in downloadData
    with open( pasta + filename, "wb") as code:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users/giovanni/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\downloadgeostatportugal/dados_INE/BGRI21_raa.zip'


Versão do Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versão do QGIS: 3.28.1-Firenze Firenze, fde3b8fbb8c 
```

**Comment by frcaldeira** [comment]
Sim é verdade Giovanni, estava a pensar resolver isto no terceiro trimestre de 2022 qquando incluir Lugares2021 e dados da Grid

**Comment by gioman** [comment]
> Sim é verdade Giovanni, estava a pensar resolver isto no terceiro trimestre de 2022 qquando incluir Lugares2021 e dados da Grid

thanks!
