### ISSUE TITLE
Erro ao descarregar os dados de Portugal/Continente

### ISSUE THREAD

**Issue by gioman** [frcaldeira/downloadgeostatportugal#5]
É de reparar que é impossível descarregar os dados de Portugal/Continente (timeout) também através do site: https://mapas.ine.pt/download/index2021.phtml

```
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) 
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "", line 3, in raise_from
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\OSGeo4W\apps\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\urllib3\util\retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "", line 3, in raise_from
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\OSGeo4W\apps\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\downloadgeostatportugal\downloadGeoStatPortugal.py", line 453, in 
    self.dlg.pB_Download.clicked.connect(lambda:self.button_DownloadData())
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\downloadgeostatportugal\downloadGeoStatPortugal.py", line 419, in button_DownloadData
    self.downloadData (SelectedGeography, SelectedYear, getChildNodeLevel)
  File "C:\Users/giovanni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\downloadgeostatportugal\downloadGeoStatPortugal.py", line 264, in downloadData
    zipresp = requests.get(url, stream = True)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

**Comment by frcaldeira** [comment]
Olá Giovanni,

Tivemos alguns problemas com a firewall que impedia o download dos ficheiros maiores (nacional e nutsII sobretudo) quer na página de download quer no plugin QGIS que partilham a mesma fonte, já está resolvido.

As nossas desculpas

Abraço
Francisco

**Comment by frcaldeira** [comment]
Solved
